# SITE CONFIGURATION
title: "Rail's Blog" # your site title
author: RailRunner16 # You :P
description: > # Meta description of Homepage
  This is my blog where I write about life, coding, and the pursuit of memes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://railrunner16.me/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Landon Gravat
  links:
    - https://twitter.com/RailRunner166
    - https://www.facebook.com/landon.gravat
    - https://github.com/railrunner166

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  I write, you enjoy.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: railinator4903@gmail.com # email for form submission

twitter_username: RailRunner166 # replace with your_twitter_username or comment to remove link from footer
github_username:  RailRunner166 # replace with your_github_username or comment to remove link from footer
instagram_username: RailRunner166 # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

theme: jekyll-sleek